language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: kalev181
  password: Sinine1989.
  api: https://api.run.pivotal.io
  organization: kalev
  space: development
